chore(deps): revert @deck.gl/layers to 8.8.9
This fixes the tests that were failing. It looks like @deck.gl uses
dependencies that were converted to esm modules and jest isn't currently
set up to handle them.

```
Jest encountered an unexpected token
...
/home/runner/work/react-map-gl/react-map-gl/node_modules/@deck.gl/layers/node_modules/@mapbox/tiny-sdf/index.js:3
export default class TinySDF {
^^^^^^

SyntaxError: Unexpected token 'export'
```

Reference: https://github.com/visgl/deck.gl/issues/7735